spring:
  application:
    name: TelRos
  datasource:
    url: jdbc:postgresql://localhost:5432/telros?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# FIle access prefix ("file:" for Linux and "file:///" for Windows)
application:
  filePrefix: file:///
  baseFileDir: C:/Temp/Pictures/
  baseDocDir: C:/Temp/doc/

logging:
  level:
    org.flywaydb: DEBUG

jwt:
  token:
    secret: dmVyeWxhcmdlYW5kY29tcGxleHNlY3JldGtleWZyb21nYW1lcGxhdGZvcm1rYXRhcHJvamVjdGFwcGxpY2F0aW9u
    expired: 84600